(2022-08-19 18:40:06.536594) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.549597) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.561600) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.574603) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.588607) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.601610) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.612612) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.624615) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.637895) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.652898) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.666901) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.679905) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.690907) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.702908) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.714912) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.727900) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.739895) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.751898) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.765901) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.778904) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.791908) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.802910) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.815913) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.827899) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.840896) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.854899) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.867903) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.880905) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.892908) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.906911) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.920915) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.934831) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.949833) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.961836) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.974838) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:06.987843) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.000845) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.015848) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.031148) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.044151) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.057154) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.071157) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.083160) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.096162) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.110165) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.123169) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.135171) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.147174) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.161177) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.173180) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.186183) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.197185) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.210188) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.224191) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.237127) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.252132) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.265134) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.277137) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.291139) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.304142) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.316145) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.330148) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.342151) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.354153) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-19 18:40:07.366156) Traceback (most recent call last):
  File "C:\Users\MrBebra\Desktop\valchecker\modules\auth.py", line 52, in auth
    r = session.post(f'https://auth.riotgames.com/api/v1/authorization', json=data, headers=headers,proxies=sys.getproxy())
  File "C:\Users\MrBebra\Desktop\valchecker\modules\systems.py", line 117, in getproxy
    nextproxy=random.choice(self.proxylist)
  File "C:\Users\MrBebra\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

_________________________________
(2022-08-22 08:15:28.872317) Traceback (most recent call last):
  File "C:\Users\hundi\OneDrive\Desktop\valchecker-main\modules\auth.py", line 30, in auth
    password=logpass.split(':')[1]
IndexError: list index out of range

_________________________________
